import { useState, useEffect } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import api from '../utils/api'

async function exportToPDF(note) {
  if (!window.jspdf) {
    await new Promise((resolve, reject) => {
      const script = document.createElement('script')
      script.src = 'https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js'
      script.onload = resolve
      script.onerror = reject
      document.head.appendChild(script)
    })
  }
  const { jsPDF } = window.jspdf
  const doc = new jsPDF()
  const pageWidth = doc.internal.pageSize.getWidth()
  const margin = 20
  const maxWidth = pageWidth - margin * 2
  let y = 20

  const addText = (text, fontSize, isBold, color) => {
    doc.setFontSize(fontSize)
    doc.setFont('helvetica', isBold ? 'bold' : 'normal')
    if (color) doc.setTextColor(...color)
    else doc.setTextColor(30, 30, 30)
    const lines = doc.splitTextToSize(text, maxWidth)
    lines.forEach(line => {
      if (y > 270) { doc.addPage(); y = 20 }
      doc.text(line, margin, y)
      y += fontSize * 0.45
    })
    y += 3
  }

  doc.setFillColor(83, 74, 183)
  doc.rect(0, 0, pageWidth, 40, 'F')
  doc.setFontSize(20); doc.setFont('helvetica', 'bold'); doc.setTextColor(255, 255, 255)
  doc.text(note.topic, margin, 22)
  doc.setFontSize(11); doc.setFont('helvetica', 'normal')
  doc.text(`${note.subject} · Generated by Study Buddy`, margin, 33)
  y = 55

  addText('SUMMARY', 13, true, [83, 74, 183])
  doc.setDrawColor(83, 74, 183); doc.line(margin, y - 2, pageWidth - margin, y - 2); y += 4
  note.summary?.forEach((point, i) => { addText(`${i + 1}. ${point}`, 11, false); y += 2 })
  y += 6

  if (note.quiz?.length > 0) {
    addText('QUIZ QUESTIONS', 13, true, [83, 74, 183])
    doc.line(margin, y - 2, pageWidth - margin, y - 2); y += 4
    note.quiz.forEach((q, i) => {
      addText(`Q${i + 1}. ${q.question}`, 11, true)
      q.options?.forEach((opt, j) => {
        const isCorrect = j === q.correct
        addText(`   ${['A','B','C','D'][j]}. ${opt}${isCorrect ? ' ✓' : ''}`, 10, isCorrect, isCorrect ? [15, 110, 86] : null)
      })
      y += 3
    })
  }
  y += 6

  if (note.flashcards?.length > 0) {
    addText('FLASHCARDS', 13, true, [83, 74, 183])
    doc.line(margin, y - 2, pageWidth - margin, y - 2); y += 4
    note.flashcards.forEach((fc, i) => {
      addText(`${i + 1}. ${fc.term}`, 11, true)
      addText(`   ${fc.definition}`, 10, false, [80, 80, 80])
      y += 2
    })
  }

  const pageCount = doc.internal.getNumberOfPages()
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i); doc.setFontSize(9); doc.setTextColor(150, 150, 150)
    doc.text(`Study Buddy · ${note.topic} · Page ${i} of ${pageCount}`, margin, 290)
  }
  doc.save(`${note.topic.replace(/\s+/g, '-')}-notes.pdf`)
}

export default function Summary() {
  const { id } = useParams()
  const navigate = useNavigate()
  const [notes, setNotes] = useState([])
  const [selected, setSelected] = useState(null)
  const [loading, setLoading] = useState(true)
  const [exporting, setExporting] = useState(false)

  useEffect(() => {
    api.get('/notes')
      .then(r => {
        setNotes(r.data)
        if (id) {
          const found = r.data.find(n => n._id === id)
          setSelected(found || r.data[0] || null)
        } else {
          setSelected(r.data[0] || null)
        }
      })
      .catch(() => setNotes([]))
      .finally(() => setLoading(false))
  }, [id])

  const deleteTopic = async (noteId, e) => {
    e.stopPropagation()
    if (!window.confirm('Delete this topic? This cannot be undone.')) return
    try {
      await api.delete(`/notes/${noteId}`)
      const updated = notes.filter(n => n._id !== noteId)
      setNotes(updated)
      if (selected?._id === noteId) setSelected(updated[0] || null)
    } catch { alert('Delete failed. Try again.') }
  }

  const handleExport = async () => {
    if (!selected) return
    setExporting(true)
    try {
      const { data } = await api.get(`/notes/${selected._id}`)
      await exportToPDF(data)
    } catch { alert('Export failed. Please try again.') }
    finally { setExporting(false) }
  }

  if (loading) return <div className="p-6 text-sm text-gray-400">Loading…</div>

  if (notes.length === 0) return (
    <div className="p-6 page-enter">
      <div className="bg-white border border-dashed border-gray-200 rounded-2xl p-12 text-center">
        <div className="text-3xl mb-3">📄</div>
        <p className="text-sm font-medium text-gray-600 mb-1">No notes yet</p>
        <p className="text-xs text-gray-400 mb-5">Upload your first notes to see summaries here.</p>
        <button onClick={() => navigate('/upload')}
          className="px-5 py-2.5 bg-primary-600 text-white text-sm font-medium rounded-lg hover:bg-primary-800 transition-colors">
          Upload notes
        </button>
      </div>
    </div>
  )

  return (
    <div className="p-6 page-enter flex gap-5">
      {/* Topic sidebar */}
      <div className="w-48 flex-shrink-0">
        <p className="text-[10px] uppercase tracking-widest text-gray-400 mb-2">Your topics</p>
        <div className="space-y-1">
          {notes.map(n => (
            <div key={n._id} onClick={() => setSelected(n)}
              className={`group px-3 py-2 rounded-lg cursor-pointer text-sm transition-colors flex items-center justify-between
                ${selected?._id === n._id ? 'bg-primary-50 text-primary-800 font-medium' : 'text-gray-600 hover:bg-gray-50'}`}>
              <div className="min-w-0">
                <p className="truncate">{n.topic}</p>
                <p className="text-xs text-gray-400 truncate">{n.subject}</p>
              </div>
              <button onClick={e => deleteTopic(n._id, e)}
                className="opacity-0 group-hover:opacity-100 ml-1 text-red-400 hover:text-red-600 transition-all flex-shrink-0"
                title="Delete">
                <svg viewBox="0 0 15 15" fill="none" className="w-3.5 h-3.5">
                  <path d="M3 3l9 9M12 3l-9 9" stroke="currentColor" strokeWidth="1.4" strokeLinecap="round"/>
                </svg>
              </button>
            </div>
          ))}
        </div>
      </div>

      {/* Summary content */}
      {selected && (
        <div className="flex-1">
          <div className="flex items-start justify-between mb-6">
            <div>
              <h1 className="font-display text-xl font-semibold">{selected.topic}</h1>
              <p className="text-sm text-gray-400 mt-0.5">{selected.subject} · {selected.summary?.length || 0} key points</p>
            </div>
            <div className="flex gap-2">
              <button onClick={handleExport} disabled={exporting}
                className="px-3 py-1.5 text-sm border border-gray-200 rounded-lg hover:bg-gray-50 transition-colors disabled:opacity-50 flex items-center gap-1.5">
                {exporting
                  ? <><span className="w-3 h-3 border-2 border-gray-300 border-t-gray-600 rounded-full animate-spin" />Exporting…</>
                  : <>
                      <svg viewBox="0 0 15 15" fill="none" className="w-3.5 h-3.5">
                        <path d="M7.5 10V2M4 7l3.5 3.5L11 7" stroke="currentColor" strokeWidth="1.3" strokeLinecap="round" strokeLinejoin="round"/>
                        <path d="M2 12h11" stroke="currentColor" strokeWidth="1.3" strokeLinecap="round"/>
                      </svg>
                      Export PDF
                    </>
                }
              </button>
              <button onClick={() => navigate(`/quiz/${selected._id}`)}
                className="px-4 py-1.5 text-sm bg-primary-600 text-white rounded-lg hover:bg-primary-800 transition-colors">
                Take quiz →
              </button>
            </div>
          </div>

          {selected.summary?.length > 0 ? (
            <div className="space-y-3">
              {selected.summary.map((point, i) => (
                <div key={i} className="flex gap-3 bg-gray-50 rounded-xl p-4">
                  <div className="w-1.5 h-1.5 rounded-full bg-primary-600 mt-2 flex-shrink-0" />
                  <p className="text-sm leading-relaxed text-gray-700">{point}</p>
                </div>
              ))}
            </div>
          ) : (
            <p className="text-sm text-gray-400">No summary available.</p>
          )}

          <div className="flex gap-3 mt-6">
            <button onClick={() => navigate(`/flashcards/${selected._id}`)}
              className="px-4 py-2 text-sm border border-gray-200 rounded-lg hover:bg-gray-50 transition-colors">
              View flashcards →
            </button>
            <button onClick={() => navigate('/upload')}
              className="text-sm text-primary-600 hover:underline px-2 py-2">
              ← Upload another topic
            </button>
          </div>
        </div>
      )}
    </div>
  )
}
