import { useState } from 'react'
import api from '../utils/api'

async function extractTextFromPDF(file) {
  if (!window.pdfjsLib) {
    await new Promise((resolve, reject) => {
      const script = document.createElement('script')
      script.src = 'https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.min.js'
      script.onload = resolve; script.onerror = reject
      document.head.appendChild(script)
    })
  }
  const pdfjsLib = window.pdfjsLib
  pdfjsLib.GlobalWorkerOptions.workerSrc = 'https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.worker.min.js'
  const arrayBuffer = await file.arrayBuffer()
  const pdf = await pdfjsLib.getDocument({ data: arrayBuffer }).promise
  let fullText = ''
  for (let i = 1; i <= pdf.numPages; i++) {
    const page = await pdf.getPage(i)
    const content = await page.getTextContent()
    fullText += content.items.map(item => item.str).join(' ') + '\n'
  }
  return fullText.trim()
}

async function exportToPDF(topic, questions) {
  if (!window.jspdf) {
    await new Promise((resolve, reject) => {
      const script = document.createElement('script')
      script.src = 'https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js'
      script.onload = resolve; script.onerror = reject
      document.head.appendChild(script)
    })
  }
  const { jsPDF } = window.jspdf
  const doc = new jsPDF()
  const pageWidth = doc.internal.pageSize.getWidth()
  const margin = 20
  const maxWidth = pageWidth - margin * 2
  let y = 20

  const addText = (text, fontSize, isBold, color) => {
    doc.setFontSize(fontSize)
    doc.setFont('helvetica', isBold ? 'bold' : 'normal')
    doc.setTextColor(...(color || [30, 30, 30]))
    const lines = doc.splitTextToSize(String(text), maxWidth)
    lines.forEach(line => {
      if (y > 275) { doc.addPage(); y = 20 }
      doc.text(line, margin, y)
      y += fontSize * 0.45
    })
    y += 2
  }

  doc.setFillColor(15, 110, 86)
  doc.rect(0, 0, pageWidth, 40, 'F')
  doc.setFontSize(18); doc.setFont('helvetica', 'bold'); doc.setTextColor(255, 255, 255)
  doc.text(`${topic} — 10 Mark Questions`, margin, 22)
  doc.setFontSize(10); doc.setFont('helvetica', 'normal')
  doc.text(`Generated by Study Buddy · ${questions.length} Questions`, margin, 33)
  y = 52

  questions.forEach((q, i) => {
    if (y > 240) { doc.addPage(); y = 20 }
    addText(`Q${i + 1}. ${q.question}`, 12, true, [30, 30, 30])
    y += 2
    const ans = q.answer
    if (typeof ans === 'string') {
      addText(ans, 10, false, [60, 60, 60])
    } else {
      if (ans.introduction) addText(ans.introduction, 10, false, [60, 60, 60])
      ans.points?.forEach(p => {
        addText(p.heading, 10, true, [15, 110, 86])
        addText(p.explanation, 10, false, [60, 60, 60])
      })
      if (ans.conclusion) addText(ans.conclusion, 10, false, [60, 60, 60])
    }
    y += 4
    doc.setDrawColor(200, 200, 200)
    doc.line(margin, y - 2, pageWidth - margin, y - 2)
    y += 5
  })

  const total = doc.internal.getNumberOfPages()
  for (let i = 1; i <= total; i++) {
    doc.setPage(i); doc.setFontSize(9); doc.setTextColor(150, 150, 150)
    doc.text(`Study Buddy · 10 Marks · Page ${i} of ${total}`, margin, 290)
  }
  doc.save(`${topic.replace(/\s+/g, '-')}-10marks.pdf`)
}

export default function TenMarks() {
  const [text, setText] = useState('')
  const [pdfFile, setPdfFile] = useState(null)
  const [extracting, setExtracting] = useState(false)
  const [loading, setLoading] = useState(false)
  const [result, setResult] = useState(null)
  const [expanded, setExpanded] = useState(new Set())
  const [dragOver, setDragOver] = useState(false)
  const [exporting, setExporting] = useState(false)

  const handleFile = async (file) => {
    if (!file || file.type !== 'application/pdf') { alert('Please upload a PDF file.'); return }
    setPdfFile(file); setText(''); setExtracting(true)
    try {
      const extracted = await extractTextFromPDF(file)
      if (!extracted || extracted.length < 30) {
        alert('Could not extract text from this PDF. Please paste text instead.')
        setPdfFile(null)
      } else { setText(extracted) }
    } catch { alert('PDF reading failed. Please paste text instead.'); setPdfFile(null) }
    finally { setExtracting(false) }
  }

  const onDrop = (e) => { e.preventDefault(); setDragOver(false); handleFile(e.dataTransfer.files[0]) }

  const generate = async () => {
    if (!text.trim()) return
    setLoading(true); setResult(null)
    try {
      const { data } = await api.post('/qna/ten-marks', { text })
      setResult(data)
      setExpanded(new Set())
    } catch (err) {
      alert(err.response?.data?.message || 'Generation failed. Try again.')
    } finally { setLoading(false) }
  }

  const toggleExpand = (i) => {
    setExpanded(prev => { const n = new Set(prev); n.has(i) ? n.delete(i) : n.add(i); return n })
  }

  return (
    <div className="p-6 max-w-3xl page-enter">
      {/* Header */}
      <div className="flex items-center justify-between mb-6">
        <div>
          <div className="flex items-center gap-2 mb-1">
            <span className="text-xs font-semibold bg-emerald-50 text-emerald-800 px-2.5 py-1 rounded-full">10 Marks</span>
          </div>
          <h1 className="font-display text-xl font-semibold">10 Mark Questions</h1>
          <p className="text-sm text-gray-400 mt-0.5">Upload any PDF or paste text — AI generates detailed structured answers.</p>
        </div>
        {result && (
          <button onClick={async () => { setExporting(true); try { await exportToPDF(result.topic, result.questions) } catch { alert('Export failed.') } finally { setExporting(false) } }}
            disabled={exporting}
            className="px-4 py-2 text-sm border border-gray-200 rounded-lg hover:bg-gray-50 transition-colors flex items-center gap-2 disabled:opacity-50">
            {exporting
              ? <><span className="w-3 h-3 border-2 border-gray-300 border-t-gray-600 rounded-full animate-spin" />Exporting…</>
              : <>
                  <svg viewBox="0 0 15 15" fill="none" className="w-3.5 h-3.5">
                    <path d="M7.5 10V2M4 7l3.5 3.5L11 7" stroke="currentColor" strokeWidth="1.3" strokeLinecap="round" strokeLinejoin="round"/>
                    <path d="M2 12h11" stroke="currentColor" strokeWidth="1.3" strokeLinecap="round"/>
                  </svg>
                  Export PDF
                </>
            }
          </button>
        )}
      </div>

      {!result && (
        <>
          <label
            onDragOver={e => { e.preventDefault(); setDragOver(true) }}
            onDragLeave={() => setDragOver(false)}
            onDrop={onDrop}
            className={`flex flex-col items-center justify-center border-2 border-dashed rounded-2xl p-8 text-center mb-4 cursor-pointer transition-colors
              ${dragOver ? 'border-emerald-400 bg-emerald-50' : 'border-gray-200 bg-gray-50 hover:bg-gray-100'}`}>
            <input type="file" accept=".pdf" className="hidden" onChange={e => handleFile(e.target.files[0])} />
            <div className="w-11 h-11 bg-emerald-50 rounded-xl flex items-center justify-center mx-auto mb-3">
              {extracting
                ? <span className="w-5 h-5 border-2 border-emerald-200 border-t-emerald-600 rounded-full animate-spin" />
                : <svg viewBox="0 0 22 22" fill="none" className="w-5 h-5">
                    <path d="M11 14V4M7 8l4-4 4 4" stroke="#0F6E56" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/>
                    <path d="M4 16v1a2 2 0 002 2h10a2 2 0 002-2v-1" stroke="#0F6E56" strokeWidth="1.5" strokeLinecap="round"/>
                  </svg>
              }
            </div>
            <p className="text-sm font-medium text-gray-700">
              {extracting ? 'Reading PDF…' : pdfFile ? pdfFile.name : <>Drop any PDF here or <span className="text-emerald-600">browse</span></>}
            </p>
            <p className="text-xs text-gray-400 mt-1">
              {pdfFile && !extracting ? `${text.length} characters extracted ✓` : 'Supports any text-based PDF'}
            </p>
          </label>

          <div className="flex items-center gap-3 mb-4 text-xs text-gray-400">
            <div className="flex-1 h-px bg-gray-100" />or paste text directly<div className="flex-1 h-px bg-gray-100" />
          </div>

          <textarea value={text} onChange={e => setText(e.target.value)}
            placeholder="Paste your notes, textbook content, or any study material here…"
            className="w-full min-h-[130px] px-4 py-3 text-sm border border-gray-200 rounded-xl focus:outline-none focus:border-emerald-400 bg-white resize-none" />

          <div className="flex items-center gap-3 mt-4">
            <button onClick={generate} disabled={loading || !text.trim()}
              className="px-5 py-2.5 bg-emerald-600 hover:bg-emerald-800 text-white text-sm font-medium rounded-lg transition-colors disabled:opacity-50 flex items-center gap-2">
              {loading
                ? <><span className="w-3.5 h-3.5 border-2 border-white/30 border-t-white rounded-full animate-spin" />Generating answers…</>
                : '⚡ Generate 10 Mark Q&A'}
            </button>
            {pdfFile && (
              <button onClick={() => { setPdfFile(null); setText('') }}
                className="px-4 py-2.5 text-sm border border-gray-200 rounded-lg hover:bg-gray-50 transition-colors">
                Clear
              </button>
            )}
          </div>
        </>
      )}

      {/* Results */}
      {result && (
        <div className="page-enter">
          <div className="flex items-center justify-between mb-4">
            <div>
              <h2 className="font-display text-lg font-semibold">{result.topic}</h2>
              <p className="text-sm text-gray-400">{result.questions?.length} questions generated</p>
            </div>
            <div className="flex gap-2">
              <button onClick={() => setExpanded(new Set(result.questions.map((_, i) => i)))}
                className="text-xs px-3 py-1.5 border border-gray-200 rounded-lg hover:bg-gray-50">Expand all</button>
              <button onClick={() => setExpanded(new Set())}
                className="text-xs px-3 py-1.5 border border-gray-200 rounded-lg hover:bg-gray-50">Collapse all</button>
              <button onClick={() => { setResult(null); setText(''); setPdfFile(null) }}
                className="text-xs px-3 py-1.5 bg-emerald-50 text-emerald-800 rounded-lg hover:bg-emerald-100">
                + New upload
              </button>
            </div>
          </div>

          <div className="space-y-2">
            {result.questions?.map((q, i) => (
              <div key={i} className="bg-white border border-gray-100 rounded-xl overflow-hidden">
                <button onClick={() => toggleExpand(i)}
                  className="w-full flex items-center justify-between px-5 py-4 text-left hover:bg-gray-50 transition-colors">
                  <div className="flex items-start gap-3">
                    <span className="text-xs font-semibold bg-emerald-50 text-emerald-700 px-2 py-0.5 rounded-full mt-0.5 flex-shrink-0">Q{i + 1}</span>
                    <p className="text-sm font-medium text-gray-800">{q.question}</p>
                  </div>
                  <svg viewBox="0 0 15 15" fill="none"
                    className={`w-4 h-4 text-gray-400 flex-shrink-0 ml-3 transition-transform ${expanded.has(i) ? 'rotate-180' : ''}`}>
                    <path d="M3 5l4.5 4.5L12 5" stroke="currentColor" strokeWidth="1.3" strokeLinecap="round" strokeLinejoin="round"/>
                  </svg>
                </button>

                {expanded.has(i) && (
                  <div className="px-5 pb-5 border-t border-gray-50 space-y-3 mt-1">
                    {typeof q.answer === 'string' ? (
                      <p className="text-sm text-gray-600 leading-relaxed">{q.answer}</p>
                    ) : (
                      <>
                        {q.answer?.introduction && (
                          <p className="text-sm text-gray-600 leading-relaxed">{q.answer.introduction}</p>
                        )}
                        {q.answer?.points?.map((p, j) => (
                          <div key={j} className="border-l-2 border-emerald-400 pl-3">
                            <p className="text-sm font-semibold text-emerald-700 mb-1">{p.heading}</p>
                            <p className="text-sm text-gray-600 leading-relaxed">{p.explanation}</p>
                          </div>
                        ))}
                        {q.answer?.conclusion && (
                          <div className="bg-gray-50 rounded-lg px-3 py-2">
                            <p className="text-xs font-semibold text-gray-500 mb-1">Conclusion</p>
                            <p className="text-sm text-gray-600 leading-relaxed">{q.answer.conclusion}</p>
                          </div>
                        )}
                      </>
                    )}
                  </div>
                )}
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  )
}
